export const DeckActionType = {
  CREATE_DECK: 'CREATE_DECK',
  DELETE_DECK: 'DELETE_DECK',
  UPDATE_DECK: 'UPDATE_DECK',
  ADD_CARD_TO_DECK: 'ADD_CARD_TO_DECK',
  REMOVE_ALL_DECKS: 'REMOVE_ALL_DECKS'
};

export const CardActionType = {
  CREATE_CARD: 'CREATE_CARD',
  DELETE_CARD: 'DELETE_CARD',
  UPDATE_CARD: 'UPDATE_CARD'
};

export const SharedActionType = {
  LOAD_STORAGE_DATA: 'LOAD_STORAGE_DATA'
};
